Comment out for debug

diff --git a/.github/workflows/update-postgresql-conf.yml b/.github/workflows/update-postgresql-conf.yml
--- a/.github/workflows/update-postgresql-conf.yml
+++ b/.github/workflows/update-postgresql-conf.yml
@@ -16,6 +16,6 @@ jobs:
       - name: Update PostgreSQL Conf
         run: |
           echo "Updating postgresql.conf..."
-          sudo -u postgres psql --tuples-only --pset format=unaligned --command 'SHOW config_file;' || echo "Error: Could not retrieve PostgreSQL config file path" >&2
-          sudo sed -i -E "/^[[:space:]]*lc_messages[[:space:]]*=/ s/^#*.*$/lc_messages = 'en_US.UTF-8'/" "$(sudo -u postgres psql --tuples-only --pset format=unaligned --command 'SHOW config_file;')" || echo "Postgres config file missing" >&2
+          # sudo -u postgres psql --tuples-only --pset format=unaligned --command 'SHOW config_file;' || echo "Error: Could not retrieve PostgreSQL config file path" >&2
+          # sudo sed -i -E "/^[[:space:]]*lc_messages[[:space:]]*=/ s/^#*.*$/lc_messages = 'en_US.UTF-8'/" "$(sudo -u postgres psql --tuples-only --pset format=unaligned --command 'SHOW config_file;')" || echo "Postgres config file missing" >&2
           echo "Updated postgresql.conf"
